### ISSUE TITLE
Docking to the right

### ISSUE THREAD

**Issue by rprieto** [TabDigital/atom-mocha-test-runner#6]
Investigate if the results window can easily be docked to the right, as a config setting.
We'll need to think about what this means if we implement the expand/collapse feature.

**Comment by DinisCruz** [comment]
I would actually like this, since that is a location I usually put my test execution resuls

**Comment by pmb0** [comment]
+1

**Comment by batjko** [comment]
Same here. I have a widescreen and splitting this way would leave plenty of space.
My problem is that I also use a terminal package (which docks to the bottom), so if I have that open as one does, opening the test results panel below as well, is covering most of my actual code editor window.

**Comment by pmb0** [comment]
Hotfix, Atom stylesheet:

```css
.mocha-test-runner {
  right: 0;
  position: fixed;
  max-width: 50%;
  height: 100%;
  top: 0;
  z-index: 1;
}

```
